Fix: Correct import path for _slugify_name function
The _slugify_name function is defined in arc.ml.runtime, not arc.ml.utils.
This was causing ImportError when saving models to the database.

Error:
  cannot import name '_slugify_name' from 'arc.ml.utils'

Fix:
  Changed import from arc.ml.utils to arc.ml.runtime in _save_model_to_db()

All 325 tests passing.